from enum import Enum


class RecordStatus(str, Enum):
    UPLOADED = "UPLOADED"
    OCR_PROCESSING = "OCR_PROCESSING"
    OCR_COMPLETE = "OCR_COMPLETE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    RECOMMENDATION_PENDING = "RECOMMENDATION_PENDING"
    RECOMMENDATION_READY = "RECOMMENDATION_READY"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXCEPTION = "EXCEPTION"