# Generated by Django 6.1.2 on 2026-10-09 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bol_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_lifting', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='UPLOADED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('line_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('e3_stock_id', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_name', models.CharField(blank=True, max_length=200, null=True)),
                ('net_gallons', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_gallons', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.billingrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('billing_record', 'line_number'), name='unique_line_number_per_record')],
            },
        ),
    ]
